export const MESSAGE_TYPES = Object.freeze({
    START: "START",
    START_ACTIVE: "START_ACTIVE",
    TEST_KEY: "TEST_KEY",
    TEST_SCREENSHOT: "TEST_SCREENSHOT",
    CONTROL: "CONTROL",
    GET_STATUS: "GET_STATUS",
    STATUS: "STATUS",
    BEGIN_QUESTION: "BEGIN_QUESTION",
    QUESTION_READY: "QUESTION_READY",
    SELECT_ANSWER: "SELECT_ANSWER",
    ANSWER_SELECTED: "ANSWER_SELECTED",
    NAVIGATE_NEXT: "NAVIGATE_NEXT",
    QUESTION_COMPLETE: "QUESTION_COMPLETE",
    QUESTION_ERROR: "QUESTION_ERROR",
    PAGE_READY: "PAGE_READY",
    INSPECT_QUESTION: "INSPECT_QUESTION",
    STOP_AUTOMATION: "STOP_AUTOMATION",
    PAUSE_AUTOMATION: "PAUSE_AUTOMATION",
    SUBMIT_TEST: "SUBMIT_TEST",
});

const messageTypeValues = new Set(Object.values(MESSAGE_TYPES));

export function isMessageType(value) {
    return messageTypeValues.has(value);
}
